import express from 'express'
import { readFileSync } from 'node:fs'
import * as https from 'node:https'
import { spawnSync } from 'node:child_process'
import { Broker } from './cloud/mqtt-broker.js'
import * as tls from 'node:tls'
import * as net from 'node:net'
import { X509Certificate } from 'node:crypto'
import { setupHttp } from './cloud/provisioning.js'
import { DeviceManager } from './cloud/devmgr.js'
import { Connection as HA_connection } from './cloud/homeassistant.js'
import HA_bridge from './cloud/ha_bridge.js'
import { Config, CA } from './util/clip.js'

import log, { setFilter as setLogFilter, error } from './util/logging.js'
import { runPreflight } from './util/preflight.js'

const app = express()

// A broken config.json used to throw here, before the preflight checks or any log filter existed,
// so the only output was a bare stack trace.
function loadConfig(): Config {
	let raw: string
	try {
		raw = readFileSync('./config.json').toString('utf-8')
	} catch(err) {
		error('status', `could not read ./config.json: ${err}`)
		error('status', '  -> entrypoint.sh generates this file from the RETHINK_* environment variables')
		process.exit(1)
	}

	try {
		return JSON.parse(raw) as Config
	} catch(err) {
		error('status', `./config.json is not valid JSON: ${err}`)
		error('status', '  -> it is generated by entrypoint.sh, so an unescaped quote in a RETHINK_* value is the usual cause')
		error('status', '  -> RETHINK_LOG in particular must be valid JSON, for example ["status","incoming"]')
		process.exit(1)
	}
}

const config = loadConfig()

if(!config.log)
	config.log = [ 'status', 'incoming' ]

// A Map, because the keys come from user configuration: an object literal would resolve topics
// like "constructor" or "toString" off Object.prototype and silently enable every log topic.
const enabled = new Map(config.log.map((key) => [ key, true ]))
setLogFilter((topic) => enabled.get(topic) || enabled.get('all') || false)

// Nothing below reports a failure loudly enough on its own, so make sure the two ways an async
// failure can vanish are always printed.
process.on('unhandledRejection', (reason) => {
	error('status', 'unhandled promise rejection:', reason)
})

process.on('uncaughtException', (err) => {
	error('status', 'uncaught exception:', err)
})

// if you add spaces here, you will have to fix quoting in the code below
// the CA is also the server
function loadOrCreateCert(): CA {
	let keypem: string, certpem: string
	try {
		keypem = readFileSync(config.ca_key_file).toString('utf-8')
		certpem = readFileSync(config.ca_cert_file).toString('utf-8')

		if(!new X509Certificate(certpem).checkHost(config.hostname))
			throw new Error("invalid subject, creating new certificate")

	} catch(err) {
		log('status', "Creating a new key/certificate for the CA")
		spawnSync('openssl', ['req', '-x509', '-newkey', 'rsa:4096', '-keyout', config.ca_key_file, '-out', config.ca_cert_file, '-sha256', '-days', '3650', '-nodes', '-subj', '/CN=' + config.hostname ])
		keypem = readFileSync(config.ca_key_file).toString('utf-8')
		certpem = readFileSync(config.ca_cert_file).toString('utf-8')
	}

	return { key: keypem, cert: certpem }
}

const ca = loadOrCreateCert()

// HTTPS server
app.use(express.json())

app.use(function(req,res, next) {
	log('HTTPS', req.hostname, req.url)
	next()
})

setupHttp(app, config, ca)

app.use((req, res) => {
	res.json({})
})

// A failed listen() used to be an uncaught EADDRINUSE with no indication of which port or which
// setting was at fault.
function reportListenError(what: string, port: number, configKey: string) {
	return (err: NodeJS.ErrnoException) => {
		if(err.code === 'EADDRINUSE')
			error('status', `${what} cannot start: port ${port} is already in use (config "${configKey}")`)
		else if(err.code === 'EACCES')
			error('status', `${what} cannot start: binding port ${port} requires privileges (config "${configKey}")`)
		else
			error('status', `${what} cannot start on port ${port} (config "${configKey}"):`, err)
	}
}

https.createServer(ca, app).listen(config.https_port)
	.on('error', reportListenError('the HTTPS server', config.https_port, 'https_port'))

// HA connector
const HA = new HA_connection(config.homeassistant)

// internal MQTT broker
const broker = new Broker()
const devices = new DeviceManager(broker)
const bridge = new HA_bridge(devices, HA)

if(config.mqtt !== false) {
	tls.createServer(ca, broker.accept.bind(broker)).listen(config.mqtts_port)
		.on('error', reportListenError('the MQTTS broker', config.mqtts_port, 'mqtts_port'))
	net.createServer({}, broker.accept.bind(broker)).listen(config.mqtt_port)
		.on('error', reportListenError('the MQTT broker', config.mqtt_port, 'mqtt_port'))
}

console.log('Rethink cloud ready')
console.log(`During setup, please ensure that connections to common.lgthinq.com:443 are redirected to ${config.hostname}:${config.https_port}`)

// Validate the configuration and actually reach out to the broker, so a misconfiguration is
// explained once here instead of being invisible.
//
// Deliberately last: the checks reach out over the network and can take tens of seconds against a
// dead broker. Running them earlier would delay generating the CA and opening the appliance
// listeners by that much, and entrypoint.sh copies the CA into /config shortly after launch.
// A bug in the checks themselves must never stop rethink from serving appliances.
try {
	await runPreflight(config, { serversStarted: true })
} catch(err) {
	error('status', 'the preflight checks could not be run:', err)
}
